Update requirements.txt
Fixing the problem where soft_unicode has been deprecated and removed from 2.1.0. 
ImportError: cannot import name 'soft_unicode' from 'markupsafe'